### ISSUE TITLE
How to make proxy authentication work in asngen.conf?

### ISSUE THREAD

**Issue by Sumanta88** [doksu/TA-asngen#23]
Hi,

In my organization there is strict rule for not allowing any unauthenticated traffic and the connection to https://download.maxmind.com/app/geoip_download/* have to go through an authenticated proxy configs.
However, I didn't found any parameter where I can mention the proxy_username and proxy_password.
Can someone please help me to know - how to make this work or this app doesn't works at all with proxy authentication.
Below is that content for my local/asngen.conf -

[splunk@np-sh-2 local]$ cat asngen.conf
[maxmind]
license_key = Gxxxxxxxxxxo7

[proxies]
https = http://outbound-service-proxy.gateway.xxxx-euw1-xxxxxxxxxxxxxxxxxxxx:80
[splunk@np-sh-2 local]$

Does adding two other parameter like below under [proxies] stanza will work?

[proxies]
https = http://outbound-service-proxy.gateway.xxxx-euw1-xxxxxxxxxxxxxxxxxxxx:80
proxy_username = blablabla
proxy_password = blablablablabla

Please advice! Thanks in advance!

**Comment by kurtkeller** [comment]
I don't have an environment at my disposal where I could test it, so the following is completely untested by me; you might want to try:

In your asngen.conf change the config for proxies to:
```
...
[proxies]
https = http://my_proxy_username:my_proxy_password@my_proxy_host:my_proxy_port
...
```
And in the asngen.py file replace lines 49-52 with:
```
        if proxies['https'] is not None:
            proxy = urllib_functions.ProxyHandler(proxies)
            auth = urllib_functions.HTTPBasicAuthHandler()
            httphandler = urllib_functions.HTTPHandler()
            opener = urllib_functions.build_opener(proxy, auth, httphandler)
            urllib_functions.install_opener(opener)
```

Again: not tested by me and I don't know whether it really works.

**Comment by Sumanta88** [comment]
Thank you so much @kurtkeller!
It worked beautifully! :)
