### ISSUE TITLE
GeoLight Deprecated, GeoLight2 is the new standard

### ISSUE THREAD

**Issue by ymylei** [doksu/TA-asngen#5]
Hi, 

I was checking out the GeoLite page, and it appears GeoLite2 (an updated format) is now the new standard and they're planning on discontinuing updates and deprecating the old GeoLite downloads.

New page is: https://dev.maxmind.com/geoip/geoip2/geolite2/

If I have some free time I can try and do a pull request to fix this and update the various Splunk pieces as well.

**Comment by doksu** [comment]
Hi @ymylei,

Thanks for raising this issue. I'm a bit busy at the moment but if you do have time a pull request would be good.

Cheers,
doksu

**Comment by nicolas-rrr** [comment]
Hi,

Download file at https://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum2.zip is no more available. I modify asngen.py file to work with the new one https://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN-CSV.zip. 

It's seems to me that it's working, you can check?

[asngen.zip](https://github.com/doksu/TA-asngen/files/2737631/asngen.zip)

Cheers,
Nicolas

**Comment by doksu** [comment]
Thanks very much for the patch @nicolas-rrr, I'm working on it now.

**Comment by doksu** [comment]
Tweaked the regex and released new version on Splunkbase.

**Comment by doksu** [comment]
@nicolas-rrr I've put credit in the release notes :)

**Comment by nicolas-rrr** [comment]
Thank you :)
